# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ForagesROIs
                                 A QGIS plugin
 Detection, classification and grid generation for forages
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-14
        copyright            : (C) 2025 by Andres Felipe Ruiz-Hurtado, Tropical Forages Program CIAT
        email                : a.f.ruiz@cgiar.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Andres Felipe Ruiz-Hurtado, Tropical Forages Program CIAT'
__date__ = '2025-05-14'
__copyright__ = '(C) 2025 by Andres Felipe Ruiz-Hurtado, Tropical Forages Program CIAT'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ForagesROIs class from file ForagesROIs.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ForagesROIs import ForagesROIsPlugin
    return ForagesROIsPlugin()
