# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ForagesROIs
                                 A QGIS plugin
 Detection, classification and grid generation for forages
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-14
        copyright            : (C) 2025 by Andres Felipe Ruiz-Hurtado, Tropical Forages Program CIAT
        email                : a.f.ruiz@cgiar.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Andres Felipe Ruiz-Hurtado, Tropical Forages Program CIAT'
__date__ = '2025-05-14'
__copyright__ = '(C) 2025 by Andres Felipe Ruiz-Hurtado, Tropical Forages Program CIAT'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider
from qgis.PyQt.QtGui import QIcon
import os
from .ForagesROIs_algorithm import ForagesROIsAlgorithm
from .plot_enumeration_algorithm import PlotEnumerationAlgorithm
from .detection_algorithm import ROIsDetectionAlgorithm
from .nms_algorithm import PostprocessingAlgorithm


class ForagesROIsProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        self.addAlgorithm(ForagesROIsAlgorithm())
        self.addAlgorithm(PlotEnumerationAlgorithm())
        self.addAlgorithm(ROIsDetectionAlgorithm())
        self.addAlgorithm(PostprocessingAlgorithm())
        # add additional algorithms here
        # self.addAlgorithm(MyOtherAlgorithm())

    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return 'ForagesROIs'

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.

        This string should be short (e.g. "Lastools") and localised.
        """
        return self.tr('ForagesROIs')

    def icon(self):
        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        return QIcon(icon_path)

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
